"use server";
import { createClient } from "@/lib/supabase/server";
import { leadershipBriefing } from "@/lib/leadership";

type AssistantAnswer={answer:string;links:{label:string;href:string}[]};
type VolunteerRow={id:string;person_id:string;people:{first_name:string|null;last_name:string|null}|{first_name:string|null;last_name:string|null}[]|null};
type AssignmentRow={id:string;status:string;starts_at:string;ends_at:string|null;role_name:string;service_id:string|null;service_position_id:string|null;volunteer_id:string};
const nameOf=(v:VolunteerRow|undefined)=>{const p=Array.isArray(v?.people)?v?.people[0]:v?.people;return [p?.first_name,p?.last_name].filter(Boolean).join(" ")||"Unnamed volunteer";};
const plural=(n:number,one:string,many=one+"s")=>`${n} ${n===1?one:many}`;
export async function askEcclesia(question:string):Promise<AssistantAnswer>{
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return{answer:"Please sign in to use Ecclesia AI.",links:[{label:"Sign in",href:"/login"}]};
 const {data:membership}=await supabase.from("church_memberships").select("church_id,role").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle(); if(!membership)return{answer:"Create your church workspace before using the assistant.",links:[{label:"Set up church",href:"/onboarding"}]};
 const churchId=membership.church_id,q=question.toLowerCase().trim(),now=new Date().toISOString();
 const [peopleResult,visitorsResult,tasksResult,journeysResult,volunteersCountResult,ministriesResult,servicesResult,volunteerRowsResult,futureAssignmentsResult]=await Promise.all([
  supabase.from("people").select("id",{count:"exact",head:true}).eq("church_id",churchId).neq("status","inactive"),supabase.from("people").select("id").eq("church_id",churchId).eq("status","visitor"),supabase.from("tasks").select("id,title,priority,due_at").eq("church_id",churchId).in("status",["open","in_progress"]),supabase.from("visitor_journeys").select("person_id,stage,next_follow_up_at").eq("church_id",churchId).neq("stage","closed"),supabase.from("volunteers").select("id",{count:"exact",head:true}).eq("church_id",churchId).eq("status","active"),supabase.from("ministries").select("id",{count:"exact",head:true}).eq("church_id",churchId).eq("active",true),supabase.from("services").select("id,name,starts_at,ends_at,status").eq("church_id",churchId).gte("starts_at",now).neq("status","cancelled").order("starts_at").limit(12),supabase.from("volunteers").select("id,person_id,people(first_name,last_name)").eq("church_id",churchId).eq("status","active"),supabase.from("service_assignments").select("id,status,starts_at,ends_at,role_name,service_id,service_position_id,volunteer_id").eq("church_id",churchId).gte("starts_at",now).in("status",["scheduled","confirmed"]).order("starts_at")]);
 const initialChecks=[peopleResult,visitorsResult,tasksResult,journeysResult,volunteersCountResult,ministriesResult,servicesResult,volunteerRowsResult,futureAssignmentsResult];
 if(initialChecks.some(result=>result.error))return{answer:"I couldn't verify all the church records needed for a reliable answer. No health score or operational conclusion has been calculated. Please try again or review the relevant workspace directly.",links:[{label:"Command Center",href:"/command-center"}]};
 const activePeople=peopleResult.count,visitors=visitorsResult.data,tasks=tasksResult.data,journeys=journeysResult.data,volunteerCount=volunteersCountResult.count,ministries=ministriesResult.count,services=servicesResult.data,volunteerRows=volunteerRowsResult.data,futureAssignments=futureAssignmentsResult.data;
 // PostgREST may cap returned rows even when the query succeeds. Refuse to score a partial dataset.
 const [taskCountResult,journeyCountResult,visitorCountResult,volunteerRowsCountResult,futureAssignmentCountResult,upcomingServiceCountResult]=await Promise.all([
  supabase.from("tasks").select("id",{count:"exact",head:true}).eq("church_id",churchId).in("status",["open","in_progress"]),
  supabase.from("visitor_journeys").select("person_id",{count:"exact",head:true}).eq("church_id",churchId).neq("stage","closed"),
  supabase.from("people").select("id",{count:"exact",head:true}).eq("church_id",churchId).eq("status","visitor"),
  supabase.from("volunteers").select("id",{count:"exact",head:true}).eq("church_id",churchId).eq("status","active"),
  supabase.from("service_assignments").select("id",{count:"exact",head:true}).eq("church_id",churchId).gte("starts_at",now).in("status",["scheduled","confirmed"]),
  supabase.from("services").select("id",{count:"exact",head:true}).eq("church_id",churchId).gte("starts_at",now).neq("status","cancelled")
 ]);
 const completenessChecks=[
  [taskCountResult,tasks?.length??0],
  [journeyCountResult,journeys?.length??0],
  [visitorCountResult,visitors?.length??0],
  [volunteerRowsCountResult,volunteerRows?.length??0],
  [futureAssignmentCountResult,futureAssignments?.length??0]
 ] as const;
 if(completenessChecks.some(([result,length])=>result.error||result.count===null||result.count!==length)||upcomingServiceCountResult.error||upcomingServiceCountResult.count===null||upcomingServiceCountResult.count>(services?.length??0)){
  return{answer:"Some church records could not be verified as complete. I cannot safely calculate a leadership score or declare a ministry queue clear. Please review the relevant workspace directly.",links:[{label:"Command Center",href:"/command-center"}]};
 }
 const serviceIds=(services??[]).map(s=>s.id); const [positionsResult,serviceAssignmentsResult]=serviceIds.length?await Promise.all([supabase.from("service_positions").select("id,service_id,role_name,required_count").eq("church_id",churchId).in("service_id",serviceIds),supabase.from("service_assignments").select("id,status,starts_at,ends_at,role_name,service_id,service_position_id,volunteer_id").eq("church_id",churchId).in("service_id",serviceIds).order("starts_at")]):[{data:[],error:null},{data:[],error:null}];
 if(positionsResult.error||serviceAssignmentsResult.error)return{answer:"I couldn't verify service planning records, so I cannot give a reliable leadership answer right now. No records were changed.",links:[{label:"Service Planning",href:"/serve"}]};
 const positions=positionsResult.data,serviceAssignments=serviceAssignmentsResult.data;
 const assignments=(serviceAssignments??[]) as AssignmentRow[],volunteers=(volunteerRows??[]) as unknown as VolunteerRow[],volunteerById=new Map(volunteers.map(v=>[v.id,v]));
 const overdueTasks=(tasks??[]).filter(t=>t.due_at&&t.due_at<now),urgentTasks=(tasks??[]).filter(t=>t.priority==="urgent"),visitorsNeedingFollowUp=(journeys??[]).filter(j=>!j.next_follow_up_at||j.next_follow_up_at<now),scheduled=assignments.filter(a=>a.status==="scheduled"),confirmed=assignments.filter(a=>a.status==="confirmed"),declined=assignments.filter(a=>a.status==="declined");
 const required=(positions??[]).reduce((sum,p)=>sum+(p.required_count??0),0),filled=assignments.filter(a=>a.service_position_id&&(a.status==="scheduled"||a.status==="confirmed")).length,vacant=Math.max(0,required-filled),staffingPct=required?Math.min(100,Math.round((filled/required)*100)):100;
 const snapshot={overdueTasks:overdueTasks.length,urgentTasks:urgentTasks.length,visitorsNeedingFollowUp:visitorsNeedingFollowUp.length,vacantServicePositions:vacant,declinedAssignments:declined.length};
 const briefing=leadershipBriefing(snapshot),leadershipSignals=briefing.signals,topSignal=leadershipSignals[0],health=briefing.health,focus=briefing.focus;
 const filledByPosition=new Map<string,number>(); for(const a of assignments)if(a.service_position_id&&(a.status==="scheduled"||a.status==="confirmed"))filledByPosition.set(a.service_position_id,(filledByPosition.get(a.service_position_id)??0)+1); const openPositions=(positions??[]).map(p=>({...p,vacant:Math.max(0,(p.required_count??0)-(filledByPosition.get(p.id)??0))})).filter(p=>p.vacant>0);
 const future=((futureAssignments??[]) as AssignmentRow[]).filter(a=>a.status==="scheduled"||a.status==="confirmed").sort((a,b)=>a.starts_at.localeCompare(b.starts_at)),byVolunteer=new Map<string,AssignmentRow[]>(); for(const a of future)byVolunteer.set(a.volunteer_id,[...(byVolunteer.get(a.volunteer_id)??[]),a]); const conflictVolunteerIds=new Set<string>(); for(const [volunteerId,list] of byVolunteer){for(let i=0;i<list.length-1;i++){const current=list[i],next=list[i+1],currentEnd=current.ends_at??new Date(new Date(current.starts_at).getTime()+7200000).toISOString();if(next.starts_at<currentEnd){conflictVolunteerIds.add(volunteerId);break;}}}
 const asksBriefing=q.includes("briefing")||q.includes("leadership summary")||q.includes("executive summary")||q.includes("morning summary"),asksVacancies=q.includes("vacant")||q.includes("unfilled")||q.includes("open position")||q.includes("positions open"),asksUnconfirmed=q.includes("hasn't confirmed")||q.includes("has not confirmed")||q.includes("not confirmed")||q.includes("awaiting confirmation")||q.includes("who hasn")||q.includes("who hasn't"),asksConflicts=q.includes("double-book")||q.includes("double book")||q.includes("conflict")||q.includes("overlap"),asksReadiness=q.includes("ready for sunday")||q.includes("sunday readiness")||q.includes("fully staffed")||q.includes("staffing readiness"),asksPriority=q.includes("priority")||q.includes("first")||q.includes("most important")||q.includes("focus on")||q.includes("focus today")||q.includes("what should i do"),asksHealth=q.includes("health score")||q.includes("operational health")||q.includes("how are we doing")||q.includes("how is the church doing"),asksPlan=q.includes("focus plan")||q.includes("top 3")||q.includes("top three")||q.includes("priorities today");
 if(asksBriefing){const priority=focus.map(i=>`${i.rank}. ${i.title}: ${i.next}`).join(" ");return{answer:`${briefing.headline}. Operational health is ${health.score}/100 — ${health.label}. ${briefing.summary} ${briefing.actionCount?`${briefing.actionCount} observable workflow items are represented in the current signals.`:"The monitored operational queue is currently clear."}${priority?` Focus plan: ${priority}`:""}`,links:[{label:"Open Leadership Insights",href:"/insights"}]};}
 if(asksHealth)return{answer:`Your current ECCLESIA operational health score is ${health.score} out of 100 — ${health.label}. ${health.summary} This score measures observable workflow conditions only; it is not a judgment of people, ministry quality, faith, or spiritual health.`,links:[{label:"Open Leadership Insights",href:"/insights"}]};
 if(asksPlan){const plan=focus.map(i=>`${i.rank}. ${i.title}: ${i.next}`).join(" ");return{answer:plan?`Your leadership focus plan is: ${plan} These are advisory priorities based on current workflow signals.`:"Your leadership focus plan is currently clear; ECCLESIA does not detect a priority workflow issue in the monitored categories.",links:[{label:"Open Leadership Insights",href:"/insights"}]};}
 if(asksPriority)return topSignal?{answer:`Your highest operational priority is ${topSignal.title.toLowerCase()}: ${topSignal.detail} Recommended next step: ${topSignal.next} This recommendation is advisory; ECCLESIA will not execute it automatically.`,links:[{label:"Review highest priority",href:topSignal.href},{label:"Leadership Insights",href:"/insights"}]}:{answer:"I do not see an urgent cross-ministry workflow issue right now. Visitor follow-up, open task urgency and upcoming service coverage are currently clear based on the available workspace data.",links:[{label:"Leadership Insights",href:"/insights"}]};
 if(asksVacancies){const details=openPositions.slice(0,8).map(p=>`${p.role_name} (${p.vacant} open)`);return{answer:openPositions.length?`There are ${vacant} unfilled service positions across upcoming services: ${details.join(", ")}${openPositions.length>8?" and more.":"."}`:"All required positions in the upcoming service plans are currently filled.",links:[{label:"Open Service Planning",href:"/serve"}]};}
 if(asksUnconfirmed){const names=scheduled.slice(0,8).map(a=>`${nameOf(volunteerById.get(a.volunteer_id))} — ${a.role_name}`);return{answer:scheduled.length?`${plural(scheduled.length,"volunteer assignment")} ${scheduled.length===1?"is":"are"} awaiting confirmation: ${names.join(", ")}${scheduled.length>8?" and more.":"."}`:"There are no upcoming service assignments awaiting confirmation.",links:[{label:"Open Serve Scheduler",href:"/serve"}]};}
 if(asksConflicts){const names=[...conflictVolunteerIds].slice(0,8).map(id=>nameOf(volunteerById.get(id)));return{answer:conflictVolunteerIds.size?`I found ${plural(conflictVolunteerIds.size,"volunteer")} with overlapping upcoming assignments: ${names.join(", ")}${conflictVolunteerIds.size>8?" and more.":"."} Please review these schedules before the services.`:"I did not find any overlapping upcoming volunteer assignments.",links:[{label:"Review Serve Scheduler",href:"/serve"}]};}
 if(asksReadiness){const nextService=services?.[0];return{answer:`${nextService?`For upcoming service planning beginning with ${nextService.name}, `:"For upcoming service planning, "}${filled} of ${required} required positions are filled (${staffingPct}% readiness). ${vacant} positions remain vacant, ${scheduled.length} assignments are awaiting confirmation, ${confirmed.length} are confirmed, and ${declined.length} have been declined.`,links:[{label:"Open Sunday Readiness",href:"/serve"},{label:"Leadership Insights",href:"/insights"}]};}
 if(q.includes("serve")||q.includes("volunteer")||q.includes("ministry")||q.includes("sunday")||q.includes("schedule"))return{answer:`Serve currently has ${volunteerCount??0} active volunteers across ${ministries??0} active ministries. Upcoming service plans require ${required} positions: ${filled} are filled, ${vacant} are vacant, ${confirmed.length} are confirmed and ${scheduled.length} are awaiting confirmation. ${declined.length} declined assignment${declined.length===1?" needs":"s need"} review.`,links:[{label:"Open Serve Scheduler",href:"/serve"}]};
 if(q.includes("visitor")||q.includes("follow up")||q.includes("follow-up"))return{answer:`You currently have ${visitors?.length??0} visitors in People and ${journeys?.length??0} active visitor journeys. ${visitorsNeedingFollowUp.length} visitor follow-up${visitorsNeedingFollowUp.length===1?" is":"s are"} overdue.`,links:[{label:"Open Visitor Journey",href:"/visitors"}]};
 if(q.includes("overdue")||q.includes("task"))return{answer:`There are ${tasks?.length??0} open ministry tasks. ${overdueTasks.length} are overdue and ${urgentTasks.length} are marked urgent.`,links:[{label:"Open Follow-Up Queue",href:"/tasks"}]};
 if(q.includes("attention")||q.includes("today"))return{answer:topSignal?`Your attention list includes ${plural(overdueTasks.length,"overdue task")}, ${plural(urgentTasks.length,"urgent task")}, ${plural(visitorsNeedingFollowUp.length,"visitor follow-up needing attention")}, ${plural(vacant,"vacant service position")}, ${plural(scheduled.length,"Serve assignment")} awaiting confirmation, and ${plural(declined.length,"declined Serve assignment")}. Highest priority: ${topSignal.title}. ${topSignal.next}`:`Your current operational attention list is clear across overdue tasks, urgent tasks, visitor follow-up needs and service vacancies.`,links:[{label:"Leadership Insights",href:"/insights"},{label:"Review priority",href:topSignal?.href??"/command-center"}]};
 if(q.includes("people")||q.includes("member")||q.includes("attendance"))return{answer:`ECCLESIA currently has ${activePeople??0} active people records and ${visitors?.length??0} people marked as visitors.`,links:[{label:"Open People CRM",href:"/people"}]};
 return{answer:`${briefing.headline}. Your church workspace has ${activePeople??0} active people, ${visitors?.length??0} visitors, ${tasks?.length??0} open tasks, and ${vacant} vacant positions across upcoming service plans. Operational health is ${health.score}/100 (${health.label}).${topSignal?` The current highest operational priority is ${topSignal.title.toLowerCase()}.`:""} Ask for a leadership briefing, health score, top three priorities, what needs attention, Sunday readiness, vacant roles, confirmations, or scheduling conflicts.`,links:[{label:"Leadership Insights",href:"/insights"},{label:"Command Center",href:"/command-center"}]};
}
