-- ECCLESIA Give foundation: tenant-safe funds and contributions.
create type public.giving_transaction_status as enum ('pending','completed','refunded','failed','voided');
create table public.giving_funds(id uuid primary key default gen_random_uuid(),church_id uuid not null references public.churches(id) on delete cascade,name text not null,description text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(church_id,id),unique(church_id,name));
create table public.contributions(id uuid primary key default gen_random_uuid(),church_id uuid not null references public.churches(id) on delete cascade,person_id uuid,fund_id uuid not null,amount numeric(12,2) not null check(amount>0),contributed_at timestamptz not null,payment_method text,reference text,status public.giving_transaction_status not null default 'completed',created_by uuid references auth.users(id),created_at timestamptz not null default now(),constraint contributions_person_tenant_fk foreign key(church_id,person_id) references public.people(church_id,id) on delete set null(person_id),constraint contributions_fund_tenant_fk foreign key(church_id,fund_id) references public.giving_funds(church_id,id));
create index contributions_church_date_idx on public.contributions(church_id,contributed_at desc); create index contributions_church_person_idx on public.contributions(church_id,person_id); create index contributions_church_fund_idx on public.contributions(church_id,fund_id);
alter table public.giving_funds enable row level security; alter table public.contributions enable row level security;
create policy "giving funds finance read" on public.giving_funds for select to authenticated using(private.has_church_role(church_id,array['owner','pastor','administrator','finance']::public.church_role[]));
create policy "giving funds finance insert" on public.giving_funds for insert to authenticated with check(private.has_church_role(church_id,array['owner','administrator','finance']::public.church_role[]));
create policy "giving funds finance update" on public.giving_funds for update to authenticated using(private.has_church_role(church_id,array['owner','administrator','finance']::public.church_role[])) with check(private.has_church_role(church_id,array['owner','administrator','finance']::public.church_role[]));
create policy "contributions finance read" on public.contributions for select to authenticated using(private.has_church_role(church_id,array['owner','pastor','administrator','finance']::public.church_role[]));
create policy "contributions finance insert" on public.contributions for insert to authenticated with check(private.has_church_role(church_id,array['owner','administrator','finance']::public.church_role[]) and created_by=(select auth.uid()));
create policy "contributions finance update" on public.contributions for update to authenticated using(private.has_church_role(church_id,array['owner','administrator','finance']::public.church_role[])) with check(private.has_church_role(church_id,array['owner','administrator','finance']::public.church_role[]));
revoke all on public.giving_funds,public.contributions from anon; grant select,insert,update on public.giving_funds,public.contributions to authenticated;
